# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: restart "{{ service_name }}"
  systemd:
    name: "{{ service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
