# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Restart "{{ service_name }}"
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
