FROM quay.io/centos-bootc/centos-bootc:stream9 AS base
RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/centos/9/tailscale.repo && \
    dnf install -y rsync tailscale qemu-guest-agent tmux firewalld && \
    dnf clean all

COPY config/base/. /

RUN ln -s /usr/lib/systemd/system/tailscaled.service /usr/lib/systemd/system/multi-user.target.wants/ && \
    ln -s /usr/lib/systemd/system/firewalld.service /usr/lib/systemd/system/multi-user.target.wants/ && \
    ln -s /usr/lib/systemd/system/cockpit.socket /usr/lib/systemd/system/multi-user.target.wants/ && \
    ln -s /usr/lib/systemd/system/qemu-guest-agent.service /usr/lib/systemd/system/multi-user.target.wants/

RUN chmod 600 /usr/lib/NetworkManager/system-connections/enp6s18.nmconnection

LABEL com.redhat.component="quay.io/aitvaras/evilcentos9:base"


FROM quay.io/aitvaras/evilcentos9:base AS evilshare
RUN dnf install -y stratisd stratis-cli samba && \
    dnf clean all

COPY config/evilshare/. /

RUN ln -s /usr/lib/systemd/system/stratisd.service /usr/lib/systemd/system/multi-user.target.wants/ && \
    ln -s /usr/lib/systemd/system/smb.service /usr/lib/systemd/system/multi-user.target.wants/ && \
    ln -s /usr/lib/systemd/system/var-storage-internal_ssd.mount /usr/lib/systemd/system/multi-user.target.wants/ && \
    ln -s /usr/lib/systemd/system/var-storage-external_hdd.mount /usr/lib/systemd/system/multi-user.target.wants/

RUN chmod 600 /usr/lib/NetworkManager/system-connections/enp6s18.nmconnection

LABEL com.redhat.component="quay.io/aitvaras/evilcentos9:evilshare"
