---
- name: setup evilservers
  hosts: all
  remote_user: "{{ main_user }}"
  become: yes
  vars:
    ansible_ssh_pass: "{{ main_user_password }}"

  pre_tasks:
    - name: update server
      tags: server-update
      block:
      - name: update server
        dnf:
          name: "*"
          state: latest
          update_cache: yes
        register: dnf_update_status
      - name: reboot server
        reboot:
        when:
          - dnf_update_status.changed


    - name: copy ssh keys
      tags: key-copy
      block:
      - name: cpy evilroots ssh key
        authorized_key:
          user: "{{ main_user }}"
          state: present
          key: "{{ evilroots_ssh_pub_key }}"
      - name: cpy evilbook ssh key
        authorized_key:
          user: "{{ main_user }}"
          state: present
          key: "{{ evilbook_ssh_pub_key }}"


  roles:
    - common
    - evilserver
