# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Setup evilcloud as evilwoods homeserver
  hosts: evilcloud
  remote_user: "{{ main_user }}"

  roles:
    - role: evilcloud
      tags: evilcloud_role
    - role: common
      tags: common_role
    - role: samba
      tags: samba_role
    - role: ntfy
      tags: ntfy_role
    - role: caddy
      tags: caddy_role
    - role: grocy
      tags: grocy_role
      # - syncthing
