- name: Setup ssh access
  hosts: evilwoods
  gather_facts: false

  tasks:
    - name: check if externl evilwoods var file exists
      delegate_to: localhost
      stat:
        path: "~/.config/evilwoods/evilwoods_ansible_vars.yml"
      register: evilwoods_ansible_vars_file

    - assert:
        that: evilwoods_ansible_vars_file.stat.exists == True
        fail_msg: "Evilwoods var file does not exist."
        quiet: true
