---
- name: setup common configuration
  hosts: all
  remote_user: "{{ main_user }}"
  become: yes

  roles:
    - common


- name: setup common configuration
  hosts: vpn
  remote_user: "{{ main_user }}"
  become: yes

  roles:
    - role: vpn
      tags:
        - wg-config


- name: setup common configuration
  hosts: evilgate
  remote_user: "{{ main_user }}"
  become: yes

  roles:
    - vpnserver