---
- name: setup connection
  hosts: evilserver
  remote_user: "{{ main_user }}"
  become: true
  vars:
    ansible_ssh_pass: "{{ main_user_password }}"
  
  tasks:
  - name: cpy ssh key
    authorized_key:
      user: "{{ main_user }}"
      state: present
      key: "{{ lookup('file', '/var/home/aitvaras/.ssh/evilserver.pub') }}"

  - name: config sshd_config
    copy:
      content: |
        PermitRootLogin no
        PasswordAuthentication no
      dest: /etc/ssh/sshd_config.d/99-custom.conf
      owner: root
      group: root
      mode: '0600'

  - name: restart sshd
    systemd:
      name: sshd
      state: restarted
