---
- name: setup test server
  hosts: test
  remote_user: "{{ main_user }}"
  become: yes
  vars_files:
    - vault.yml
  vars:
    ansible_become_password: "{{ main_user_password }}"

  tasks:
  - name: wait for os to bootup
    wait_for_connection:

  roles:
    - common