# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Setup ssh access
  hosts: evilwoods
  remote_user: "{{ main_user  }}"
  tasks:
    - name: Upload ssh keys
      ansible.posix.authorized_key:
        user: "{{ main_user }}"
        state: present
        key: "{{ item }}"
      with_items:
        - "{{ evilroots_ssh_key }}"

    - name: Config sshd_config
      become: true
      ansible.builtin.copy:
        content: |
          PermitRootLogin no
          PasswordAuthentication no
        dest: /etc/ssh/sshd_config.d/99-evilserver.conf
        owner: root
        group: root
        mode: '0600'
      notify: restart sshd
