---
- name: setup common configuration
  hosts: all
  remote_user: "{{ main_user }}"
  become: yes
  vars:
    ansible_become_password: "{{ main_user_password }}"

  roles:
    - common

- name: setup common configuration
  hosts: vpn
  remote_user: "{{ main_user }}"
  become: yes
  vars:
    ansible_become_password: "{{ main_user_password }}"

  roles:
    - role: vpn
      tags:
        - wg-config