# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Import ssh access setup paybook
  ansible.builtin.import_playbook:
    file: setup_ssh_access.yml

- name: Import main paybook
  ansbile.builtin.import_playbook:
    file: evilserver..yml
