# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Import ssh access setup paybook
  ansible.builtin.import_playbook:
    playbooks/setup_ssh_access.yml

- name: Import tailscale setup paybook
  ansible.builtin.import_playbook:
    playbooks/setup_ssh_access.yml

- name: Import main paybook
  ansible.builtin.import_playbook:
     evilcloud.yml
