---
all:
  hosts:
  children:
    vpn:
      hosts:
        vpnserver:
          ansible_host: 135.181.85.62
      children:
        vpnclients:
          hosts:
            testclient:
              ansible_host: 135.181.27.72
            