---
- name: update all servers
  hosts: all
  remote_user: "{{ main_user }}"
  become: yes

  tasks:
    - name: update server
      dnf:
        name: '*'
        state: latest
        update_cache: yes
    - name: reboot server
      reboot:
