---
- name: update all servers
  hosts: all
  remote_user: "{{ main_user }}"
  become: yes
  vars:
    ansible_become_password: "{{ main_user_password }}"

  tasks:
    - name: update server
      dnf:
        name: '*'
        state: latest
        update_cache: yes
    - name: reboot server
      reboot: