# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Update and reboot The OS
  hosts: evilwoods
  remote_user: "{{ main_user }}"
  become: true
  tasks:
#    - name: Update all packages
#      become: true
#      ansible.builtin.dnf:
#        name: '*'
#        state: latest
#        update_cache: true
#        update_only: true
    - name: Edit rpm-ostreed.conf
      ansible.builtin.lineinfile:
        path: /etc/rpm-ostreed.conf
        regexp: '^#?AutomaticUpdatePolicy=.*'
        line: 'AutomaticUpdatePolicy=apply'
        state: present
        backup: true

    - name: Save rmp-ostreed-automatic.timer overrides
      ansible.builtin.copy:
        content: |
          [Timer]
          OnBootSec=
          OnUnitInactiveSec=
          OnCalendar=*-*-* 03:00:00
          AccuracySec=1h
          RandomizedDelaySec=1h
        dest: /etc/systemd/system/rpm-ostreed-automatic.timer.d/override.conf
        owner: root
        group: root
        mode: "0644"
        backup: true

    - name: Eable and start rpm-ostreed-automatic.timer
      ansible.builtin.systemd:
        name: rpm-ostreed-automatic.timer
        state: started
        enabled: true

    - name: Update rpm-ostree system
      ansible.posix.rpm_ostree_upgrade:
      notify:
        - Reboot the OS

  handlers:
    - name: Reboot the OS
      ansible.builtin.reboot:
