---
- name: stop "{{ container_name }}" service
  systemd:
    scope: user
    name: "container_{{ container_name }}"
    state: stopped
  ignore_errors: true

- name: "create {{ container_name }} container"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}:{{ image_tag }}"
    state: created
    detach: true
    tty: true
    force_restart: true
    ports:
      - "{{ host_port }}:{{ container_port }}"
      - "{{ host_tls_port }}:{{ container_tls_port }}"
    volumes:
      - "{{ ansible_env.HOME }}/{{ config }}/Caddyfile:/etc/caddy/Caddyfile:Z"
      - "{{ ansible_env.HOME }}/{{ data }}:/data:Z"
    labels:
      - io.containers.autoupdate: registry


- name: "generate {{ container_name }} service files"
  containers.podman.podman_generate_systemd:
    name: "{{ container_name }}"
    use_names: true
    separator: "_"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user"

- name: enable "{{ container_name }}" container service
  systemd:
    scope: user
    name: "container_{{ container_name }}"
    enabled: true
    state: started
    daemon_reload: true
