---
- name: redirect ports 80
  become: true
  firewalld:
    zone:  public
    port_forward:
      - port: 80
        proto: tcp
        toport: 8080
    state: enabled
    immediate: true
    permanent: true

- name: redirect ports 443
  become: true
  firewalld:
    zone:  public
    port_forward:
      - port: 443
        proto: tcp
        toport: 8443
    state: enabled
    immediate: true
    permanent: true

- name: create and run caddy container
  containers.podman.podman_container:
    name: "{{ caddy_container_name }}"
    image: docker.io/library/caddy:latest
    state: started
    detach: true
    tty: true
    force_restart: true
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "/home/{{ main_user }}/Containers/data/caddy/Caddyfile:/etc/caddy/Caddyfile:Z"
      - "/home/{{ main_user }}/Containers/data/caddy/data:/data:Z"
    generate_systemd:
      names: true
      new: true
      separator: "_"
      path: "/home/{{ main_user }}/.config/systemd/user"

- name: enable "{{ caddy_container_name }}" container service
  systemd:
    scope: user
    name: "container_{{ caddy_container_name }}"
    enabled: true
    state: started
    daemon_reload: true
