---
- name: redirect ports 80
  become: true
  firewalld:
    zone:  public
    port_forward:
      - port: 80
        proto: tcp
        toport: 8080
    state: enabled
    immediate: true
    permanent: true

- name: redirect ports 443
  become: true
  firewalld:
    zone:  public
    port_forward:
      - port: 443
        proto: tcp
        toport: 8443
    state: enabled
    immediate: true
    permanent: true

- name: create and run caddy container
  containers.podman.podman_container:
    name: evil_caddy
    image: docker.io/library/caddy:latest
    state: started
    recreate: true
    detach: true
    tty: true
    force_restart: true
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "/home/{{ caddy_container_user }}/Containers/data/caddy/Caddyfile:/etc/caddy/Caddyfile:Z"
      - "/home/{{ caddy_container_user }}/Containers/data/caddy/data:/data:Z"
