# vim: filetype=yaml.ansible
---
- name: Ensure that systemd container dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd"
    state: directory
    recurse: true

- name: Create systemd quadlet file "{{ service }}"
  vars:
    config: "{{ ansible_env.HOME }}/{{ config_dir }}"
    data: "{{ ansible_env.HOME }}/{{ data_dir }}"
  ansible.builtin.template:
    src: evilcaddy.container.j2
    dest: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ service_name }}.container"
    mode: '644'
  notify:
    - "restart {{ service_name }}"
