---
- name: ensure that systemd container dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd"
    state: directory
    recurse: yes

- name: create "{{ service }} systemd quadlet file"
  vars:
    config: "{{ ansible_env.HOME }}/{{ config_dir }}"
    data: "{{ ansible_env.HOME }}/{{ data_dir }}"
  template:
    src: evilcaddy.container.j2
    dest: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ service_name }}.container"
  notify:
    - "restart {{ service_name }}"
