# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Include caddy firewall setup tasks
  ansible.builtin.include_tasks:
    file: caddy_firewall_setup.yml
    apply:
      become: true
      tags:
        - caddy_firewall
  tags:
    - caddy_firewall

- name: Include caddy setup tasks
  ansible.builtin.include_tasks:
    file: caddy_setup.yml
    apply:
      become_user: "{{ user }}"
      tags:
        - caddy_service
  tags:
    - caddy_service
