# vim: filetype=yaml.ansible
---
- include_tasks:
    file: caddy_firewall_setup.ansible.yml
    apply:
      become: true
      tags:
        - caddy_firewall
  tags:
    - caddy_firewall

- include_tasks:
    file: caddy_setup.ansible.yml
    apply:
      become_user: "{{ user }}"
      tags:
        - caddy_service
  tags:
    - caddy_service
