---
ansible_ssh_pass: "{{ main_user_password }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no \
                          -o PreferredAuthentications=password \
                          -o PubkeyAuthentication=no'
