# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: restart cockpit
  systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: yes
