# code: language=ansible
---
# main user information
main_user: aitvaras
ansible_become_password: "{{ main_user_password }}"

# keys to add to authorized keys
evilroots_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGFc8oFtu7i4WBlbcDMB7ua9cHJW2bzeomrLFddokw7v aitvaras@evilbook"

user_quadlet_path: "/home/{{ main_user }}/.config/containers/systemd"

volume_directory: Containers

# restic service
restic_service_name: backup
restic_config_dir: "{{ volume_directory }}/{{ restic_service_name }}/config"
restic_image: docker.io/restic/restic
restic_image_tag: latest
restic_repo_path: s3:s3.eu-central-003.backblazeb2.com/evilcloud-data-backup

tailscale_zone: trusted
