# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted

- name: Restart cockpit
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Reboot host
  ansible.builtin.reboot:
