---
pod_name: evilgrocy
container_user: "{{ main_user }}"
host_port: 8081
pod_port: 8080
backend_name: "{{ pod_name }}_backend"
backend_image: "docker.io/grocy/backend"
backend_version: v4.0.0
frontend_name: "{{ pod_name }}_frontend"
frontend_version: v4.0.0
frontend_image: "docker.io/grocy/frontend"
