---
container_user: "{{ main_user }}"
pod_name: evilgrocy
host_port: 8081
pod_port: 8080
data: "{{ volume_directory }}/grocy/data"
folder_to_backup: grocy
backend_name: "{{ pod_name }}_backend"
tag: "{{ pod_name }}"
backend_image: "docker.io/grocy/backend"
backend_version: v4.0.0
frontend_name: "{{ pod_name }}_frontend"
frontend_version: v4.0.0
frontend_image: "docker.io/grocy/frontend"
