---
- name: install wireguard packages
  dnf:
    name: wireguard-tools
    state: present

- name: install wireguard kernel module
  block:
    - name: install the module 
      dnf:
        name:
          - kmod-wireguard
        state: present
    
    - name: load wg module
      modprobe:
        name: wireguard
        state: present
  when: ansible_facts['distribution'] == 'Centos'

- name: check if private key exists
  become_user: root
  stat:
    path: "{{ wireguard_directory }}/privatekey"
  register: wireguard_register_conf_file

- name: generate new keys
  become: true
  become_user: root
  block:
    - name: create directory
      file:
        path: "{{ wireguard_directory }}"
        state: directory
        owner: root
        mode: '0700'

  
