---
- name: install wireguard packages
  dnf:
    name: wireguard-tools
    state: present
  tags:
    - wg-install

- name: install wireguard kernel module
  block:
    - name: install the module 
      dnf:
        name:
          - kmod-wireguard
        state: present
    
    - name: load wg module
      modprobe:
        name: wireguard
        state: present
  when: ansible_facts['distribution'] == 'Centos'
  tags:
    - wg-install

- name: check if private key exists
  become_user: root
  stat:
    path: "{{ wireguard_directory }}/privatekey"
  register: wireguard_register_conf_file
  tags:
    - wg-gen-keys

- name: generate new private key
  become: true
  become_user: root
  block:
    - name: create directory
      file:
        path: "{{ wireguard_directory }}"
        state: directory
        owner: root
        group: root
        mode: '0700'
    
    - name: generate privete key
      command: wg genkey
      register: wireguard_register_private_key
    
    - name: save key to file
      copy:
        content: "{{ wireguard_register_private_key.stdout }}"
        dest: "{{ wireguard_directory }}/privatekey"
        owner: root
        group: root
        mode: '0600'
  when:
    - not wireguard_register_conf_file.stat.exists
  tags:
    - wg-gen-keys

- name: generate public key
  become: true
  become_user: root
  block:
    - name: read private key from file
      slurp:
        src: "{{ wireguard_directory }}/privatekey"
      register: wireguard_register_private_key_file

    - name: set private key fact
      set_fact:
        wireguard_private_key: "{{ wireguard_register_private_key_file['content'] | b64decode }}"

    - name: generate public key
      command: wg pubkey
      args:
        stdin: "{{ wireguard_private_key }}"
      register: wireguard_register_public_key
    
    - name: set public key fact
      set_fact:
        wireguard_public_key: "{{ wireguard_register_public_key.stdout }}"
    
    - name: save public key to file
      copy:
        content: "{{ wireguard_register_public_key.stdout }}"
        dest: "{{ wireguard_directory }}/publickey"
        force: yes # overwrites file if content differs
        owner: root
        group: root
        mode: '0600'
      when:
        - not wireguard_register_conf_file.stat.exists
    
    - name: fetch wg server public key
      fetch:
        src: "{{ wireguard_directory }}/publickey"
        dest: "../wg"
      when:  inventory_hostname == 'vpnserver'
  tags:
    - wg-gen-keys
    
- name: genereate wireguard config
  become_user: root
  become: true
  template:
    src: etc/wireguard/wg.conf.j2
    dest: "{{ wireguard_directory }}/{{ wireguard_interface }}.conf"
    owner: "{{ wireguard_config_owner }}"
    group: "{{ wireguard_config_group }}"
    mode: "{{ wireguard_config_mode }}"


- name: configire firewall for wg
  block:
    - name: add internal network interface to trusted zone
      firewalld:
        interface: eth1
        zone: trusted
        state: enabled
        permanent: yes
        immediate: yes
    
    - name: add source for eth1 interface
      firewalld:
        zone: trusted
        source: "{{ vps_internal_net }}"
        permanent: yes
        immediate: yes
        state: enabled

    - name: add internal network interface to trusted zone
      firewalld:
        interface: wg0
        zone: trusted
        state: enabled
        permanent: yes
        immediate: yes

    - name: add source for wg0 interface
      firewalld:
        zone: trusted
        permanent: yes
        immediate: yes
        source: "{{ vps_wireguard_net }}"
        state: enabled
    
  tags:
    - wg-firewall




  
