---
- name: add tailscale reposotory
  get_url:
    url: https://pkgs.tailscale.com/stable/centos/9/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    mode: 0644


- name: install packages
  block:
    - name: enable epel
      dnf:
        name:
          - epel-release
        state: present
      when:
        - ansible_facts['distribution'] == 'CentOS'

    - name: install packages
      dnf:
        name:
          - tmux
          - fish
          - neovim
          - python3-neovim
          - tailscale
          - toolbox
          - podman
        state: present
        update_cache: yes
  tags:
    - package-installation

- name: enalbe tailscale daemon
  systemd:
    name: tailscaled
    state: started
    enabled: yes

- name: config sshd_config
  copy:
    content: |
      PermitRootLogin no
      PasswordAuthentication no
    dest: /etc/ssh/sshd_config.d/99-evilserver.conf
    owner: root
    group: root
    mode: '0600'