---
- name: add tailscale reposotory
  get_url:
    url: https://pkgs.tailscale.com/stable/centos/9/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    mode: 0644


- name: install packages
  block:
    - name: enable epel
      dnf:
        name:
          - epel-release
        state: present
      when:
        - ansible_facts['distribution'] == 'CentOS'

    - name: install packages
      dnf:
        name:
          - tmux
          - fish
          - neovim
          - python3-neovim
          - tailscale
          - toolbox
          - podman
        state: present
        update_cache: yes
  tags:
    - package-installation

# TODO move tailscale into a block. Block runs if tailscale service is not up and connected.
- name: enable tailscale daemon
  systemd:
    name: tailscaled
    state: started
    enabled: yes

- name: check tailscale status
  command: tailscale status
  register: tailscale_status
  changed_when: false           # nothing changes here but ansible reports changed
  failed_when:
    - tailscale_status.rc != 0
    - "'Logged out.' not in tailscale_status.stdout"

- name: check if tailscale key is defined
  assert:
    that:
      - tailscale_key is defined
    quiet: true
    fail_msg: "Tailscale_key not found. Provide tailscale key with --extra-vars 'tailscale_key=...' argument"
    success_msg: "Tailscale_key found"
  register: tailscale_key_assert
  ignore_errors: true
  when:
    - tailscale_status.rc != 0
    - "'Logged out.' in tailscale_status.stdout"

- name: Bring tailscale up
  command: tailscale up --auth-key "{{ tailscale_key }}"
  no_log: true
  register: tailscale_up_status
  when:
    - tailscale_status.rc != 0
    - "'Logged out.' in tailscale_status.stdout"
    - not tailscale_key_assert.failed
  changed_when: tailscale_up_status.rc == 0

- name: read tailscale address
  command: tailscale ip -4
  changed_when: false
  register: tailscale_ip_status

- name: create cockpit socket config 'distribution'
  file:
    path: /etc/systemd/system/cockpit.socket.d/
    state: directory

- name: write cockpit conf
  copy:
    content: |
      [Socket]
      ListenStream=
      ListenStream={{ tailscale_ip_status.stdout }}:9090
      FreeBind=yes
    dest: /etc/systemd/system/cockpit.socket.d/listen.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - tailscale_ip_status.rc == 0

- name: start cockpit Socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: config sshd_config
  copy:
    content: |
      PermitRootLogin no
      PasswordAuthentication no
    dest: /etc/ssh/sshd_config.d/99-evilserver.conf
    owner: root
    group: root
    mode: '0600'