# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Include cockpit setup tasks
  ansible.builtin.include_tasks:
    file: setup_cockpit.yml
    apply:
      tags:
        - setup_cockpit

- name: Include package related tasks
  ansible.builtin.include_tasks:
    file: setup_common_packages.yml
    apply:
      tags:
        - setup_common_packages
