# vim: filetype=yaml.ansible
---
- include_tasks:
    file: update_system.yml
    apply:
      tags:
        - update_system
  tags:
    - update_system

- include_tasks:
    file: setup_ssh_access.yml
    apply:
      tags:
        - setup_ssh_access
  tags:
    - setup_ssh_access

- include_tasks:
    file: setup_tailscale.yml
    apply:
      tags:
        - setup_tailscale
  tags:
    - setup_tailscale

- include_tasks:
    file: setup_cockpit.yml
    apply:
      tags:
        - setup_cockpit
  tags:
    - setup_cockpit

- include_tasks:
    file: setup_common_packages.yml
    apply:
      tags:
        - setup_common_packages
  tags:
    - setup_common_packages
