---
- include_tasks:
    file: update_system.yml
    apply:
      tags:
        - system_update
  tags:
    - update_system_tasks

- include_tasks:
    file: setup_ssh_access.yml
    apply:
      tags:
        - ssh_access_setup
  tags:
    - ssh_access_tasks

- include_tasks:
    file: setup_tailscale.yml
    apply:
      tags:
        - tailscale_setup
  tags:
    - tailscale_tasks

- include_tasks:
    file: setup_cockpit.yml
    apply:
      tags:
        - cockpit_setup
  tags:
    - cockpit_tasks

- include_tasks:
    file: setup_common_packages.yml
    apply:
      tags:
        - common_packages_setup
  tags:
    - common_packages_tasks
