---
- name: wait for server to reboot
  wait_for_connection:

- name: update packages
  dnf:
    name: '*'
    state: latest
    update_cache: yes
  tags:
    - pkg-update

- name: enable centos extra repos
  dnf:
    name:
      - epel-release
      - elrepo-release
    state: present
  when: ansible_facts['distribution'] == "Centos"

- name: install packages
  dnf:
    name:
      - firewalld
      - tmux
      - cockpit
    state: present
  notify:
    - restart firewalld
    - restart cockpit
  tags: pkg-install

- name: start firewalld
  systemd:
    service: firewalld
    state: started
    enabled: yes

- name: configure firewalld
  block:
    - name: add cockpit port
      ansible.posix.firewalld:
        service: cockpit
        state: enabled
        immediate: yes
        permanent: yes
  tags:
    - fw-config

#- name: check if keys exists
  