# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Include cockpit setup tasks
  ansible.builtin.import_tasks:
    file: setup_cockpit.yml
  tags: setup_cockpit_tasks

- name: Include package related tasks
  ansible.builtin.import_tasks:
    file: setup_common_packages.yml
  tags: setup_common_packages_tasks
