---
- name: wait for server to reboot
  wait_for_connection:

- name: add tailscale reposotory
  get_url:
    url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    mode: 0644

- name: install packages
  block:
    - name: install packages
      dnf:
        name:
          - tmux
          - fish
          - neovim
          - fzf
          - bat
          - python3-neovim
          - tailscale
          - toolbox
          - podman
        state: present
  tags:
    - install-packages

- name: enalbe tailscale daemon
  systemd:
    name: tailscaled
    state: started
    enabled: yes


- name: check if tailscale was connected prevously
  stat:
    path: "/home/{{ main_user }}/.tailscale_connected"
  register: tailscale_connected

- name: connect to tailscale
  block:
    - name: connect with key
      shell: tailscale up --authkey "{{ tailscalekey }}"
    - name: create a tailscale_connected file
      file:
        path: "/home/{{ main_user }}/.tailscale_conencted"
        state: touch
  when: tailscale_connected.stat.exists

- name: close ports
  block:
    - name: close cockpit
      firewalld:
        service: cockpit
        permanent: yes
        state: disabled

    - name: close ssh
      firewalld:
        service: ssh
        permanent: yes
        state: disabled
