# vim: filetype=yaml.ansible
---
- name: Close cockpit port in public zone
  become: true
  ansible.posix.firewalld:
    zone: public
    service: cockpit
    state: disabled
    permanent: true
    immediate: true

- name: Enable cockpit service socket
  become: true
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
