# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Install common packages
  become: true
  ansible.builtin.dnf:
    name:
      - tmux
      - toolbox
      - fail2ban
      - fish
    state: present
