# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Update all packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
  notify: reboot host
