# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Import ssh access setup paybook
  ansible.builtin.import_playbook:
    playbooks/setup_ssh_access.yml
  tags:
    - access_setup
    - setup_ssh_access_play

- name: Import tailscale setup paybook
  ansible.builtin.import_playbook:
    playbooks/setup_tailscale.yml
  tags:
    - access_setup
    - setup_tailscale_play

- name: Import main paybook
  ansible.builtin.import_playbook:
    evilcloud.yml
  tags: evilcloud_play
