---
# caddy
user: "{{ main_user }}"
service_name: evilcaddy
image_path: docker.io/library/caddy
image_tag: latest
image: "{{ image_path }}:{{ image_tag }}"
config_dir: "{{ volume_directory }}/caddy/config"
data_dir: "{{ volume_directory }}/caddy/data"

unit_file_name: "container_{{ service_name }}"
 
mage_tag: latest
host_port: 8080
host_tls_port: 8443
container_port: 80
container_tls_port: 443


