# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Setup evilcloud as evilwoods homeserver
  hosts: evilcloud
  remote_user: "{{ main_user }}"

  roles:
    - role: common
      tags: common_tasks
    - role: samba
      tags: samba_tasks
    - role: caddy
      tags: caddy_tasks
    - role: grocy
      tags: grocy_tasks
      # - syncthing
