# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Syncthing
  tags: syncthing-setup
  block:
    - name: Create syncthing container
      become: false
      containers.podman.podman_container:
        name: evilsync
        image: "{{ syncthing_image }}"
        hostname: evilserver
        env:
          PUID: 0
          PGID: 0
        ports:
          - 22000:22000/tcp
          - 22000:22000/udp
          - 21027:21027/tcp
          - 8384:8384       # gui
        volumes:
          - "/home/{{ main_user }}/data/syncthing:/var/syncthing:Z"
        label:
          io.containers.autoupdate: registry
        generate_systemd:
          names: true
          new: true
          path: "/home/{{ main_user }}/.config/systemd/user/"

    - name: Enable generated evilsync service
      become: false
      ansible.builtin.systemd:
        name: container-evilsync
        scope: user
        enabled: true
        state: started
        daemon_reload: true

    - name: Open syncthing port
      ansible.posix.firewalld:
        zone: "{{ tailscale_zone }}"
        service: syncthing
        state: enabled
        permanent: true

    - name: Open syncthing-gui port
      ansible.posix.firewalld:
        zone: "{{ tailscale_zone }}"
        service: syncthing-gui
        state: enabled
        permanent: true
