# vim: filetype=yaml.ansible
---
- name: Check if directories exists"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ quadlet_dir }}"
    - "{{ config_dir }}"
    - "{{ data_dir }}"

- name: Create systemd quadlet file "{{ service_name }}"
  vars:
    data: "{{ ansible_env.HOME }}/{{ data_dir }}"
  ansible.builtin.template:
    src: evilgrocy.container.j2
    dest: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ service_name }}.container"
    mode: '644'
  notify:
    - "Restart {{ service_name }}"
