# vim: filetype=yaml.ansible
---
- name: "create {{ service_name }} restic backup envronment file"
  template:
    src: restic_backup.env.j2
    dest: "{{ ansible_env.HOME }}/{{ restic_backup_config_dir }}/restic_backup.env"
    mode: '600'

- name: Create backup service {{ service_name }}"
  vars:
    restic_backup_cont_name: "{{ service_name }}_backup"
    conflicts: "{{ service_name }}.service"
    tag: "{{ service_name }}"
  ansible.bluiltin.template:
    src: restic_backup.service.j2
    dest: "{{systemd_unit_dir }}/{{ service_name }}_{{ restic_service_name }}.service"
    mode: '644'
  notify:
    - "restart {{ service_name }} timer"

- name: "create {{ service_name }} restic backup timer"
  template:
    src: restic_backup.timer.j2
    dest: "{{ systemd_unit_dir }}/{{ service_name }}_{{ restic_service_name }}.timer"
    mode: '600'
  notify:
    - "restart {{ service_name }} timer"

