# vim: filetype=yaml.ansible
---
- name: Check if directories exists"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ quadlet_dir }}"
    - "{{ config_dir }}"
    - "{{ data_dir }}"

- name: Create kube yaml file "{{ service_name }}"
  ansible.builtin.template:
    src: evilgrocy.kube.yml.j2
    dest: "{{ config_dir }}/{{ service_name }}.kube.yml"
    mode: '644'
  notify:
    - "Restart {{ service_name }}"

- name: Create kube file "{{ service_name }}"
  ansible.builtin.template:
    src: evilgrocy.kube.j2
    dest: "{{ quadlet_dir }}/{{ service_name }}.kube"
    mode: '644'
  notify:
    - "Restart {{ service_name }}"
