---
- name: check if "{{ item }} exists"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ quadlet_dir }}"
    - "{{ config_dir }}"
    - "{{ data_dir }}"

- name: create "{{ service_name }} kube file"
  template:
    src: evilgrocy.kube.yml.j2
    dest: "{{ config_dir }}/{{ service_name }}.kube.yml"

- name: create "{{ service_name }} kube file"
  template:
    src: evilgrocy.kube.j2
    dest: "{{ quadlet_dir }}/{{ service_name }}.kube"
  notify:
    - "restart {{ service_name }}"


