---
- include_tasks:
    file: grocy_setup.yml
    apply:
      become_user: "{{ container_user }}"
      tags:
        - grocy_service
  tags:
    - grocy_service

- include_tasks:
    file: grocy_backup_setup.yml
    apply:
      become_user: "{{ container_user }}"
      tags:
        - grocy_backup
  tags:
    - grocy_backup
