# code: language=ansible
# vim: filetype=yaml.ansible
---
- name: Include grocy setup tasks
  ansible.builtin.include_tasks:
    file: grocy_setup.ansible.yml
    apply:
      become_user: "{{ user }}"
      tags:
        - grocy_service
  tags:
    - grocy_service

- name: Include grocy backup setup tasks
  ansible.builtin.include_tasks:
    file: grocy_backup_setup.ansible.yml
    apply:
      become_user: "{{ user }}"
      tags:
        - grocy_backup
  tags:
    - grocy_backup
