# vim: filetype=yaml.ansible
---
- include_tasks:
    file: grocy_setup..ansible.yml
    apply:
      become_user: "{{ user }}"
      tags:
        - grocy_service
  tags:
    - grocy_service

- include_tasks:
    file: grocy_backup_setup.ansible.yml
    apply:
      become_user: "{{ user }}"
      tags:
        - grocy_backup
  tags:
    - grocy_backup
